### ISSUE TITLE
GHC 7.10 support

### ISSUE THREAD

**Issue by geraldus** [chrisdone/ghci-ng#15]
I've tried to build **ghci-ng** with GHC version 7.10.1 (modified dependency `ghc == 7.10.1`) and failed:

```
Preprocessing executable 'ghci-ng' for ghci-ng-0.0.0...
[1 of 8] Compiling GhciTypes        ( ghc/GhciTypes.hs, dist/build/ghci-ng/ghci-ng-tmp/GhciTypes.o )
[2 of 8] Compiling GhciMonad        ( ghc/GhciMonad.hs, dist/build/ghci-ng/ghci-ng-tmp/GhciMonad.o )

ghc/GhciMonad.hs:54:1: Warning:
    The import of ‘Control.Applicative’ is redundant
      except perhaps to import instances from ‘Control.Applicative’
    To import instances alone, use: import Control.Applicative()
[3 of 8] Compiling GhciTags         ( ghc/GhciTags.hs, dist/build/ghci-ng/ghci-ng-tmp/GhciTags.o )
[4 of 8] Compiling GhciInfo         ( ghc/GhciInfo.hs, dist/build/ghci-ng/ghci-ng-tmp/GhciInfo.o )

ghc/GhciInfo.hs:185:67:
    Not in scope: type constructor or class ‘PostTcType’
    Perhaps you meant one of these:
      ‘PostTcExpr’ (imported from GHC), ‘PostTcTable’ (imported from GHC)
```

My knowledge do not let me go any further, and I don't know is it hard to make build successful.

Can you give any explanations or clarifications?

**Comment by chrisdone** [comment]
I haven't tried it on GHC 7.10 yet. Probably a case of adding some ifdef's against the new API.

**Comment by schell** [comment]
I've started some progress in my fork at https://github.com/schell/ghci-ng/commit/1f7a32f457e20e8c33a697936aee19af7bd9042e

**Comment by geraldus** [comment]
@schell oh cool, I'm rather far from such GHC internals things.

**Comment by chrisdone** [comment]
@schell neat

**Comment by geraldus** [comment]
oh, great! (:

**Comment by chrisdone** [comment]
It doesn't build for me on my GHC 7.10 version but I'll try the official release later.

**Comment by geraldus** [comment]
Successfully built with GHC 7.10.1.

**Comment by PierreR** [comment]
Any plan to release ghc-7.10.x support to hackage/stackage ?

Cheers,
